#### **1. Introduction to NumPy**

**Task 1**: Import the NumPy library and print its version.

In [ ]:
# Write your answer from this cell onwards
import numpy as np
print(np.__version__)

1.26.4


**Task 2**: Create a one-dimensional NumPy array of integers from 0 to 9 and print it.

In [ ]:
# Write your answer from this cell onwards

array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(array)

[0 1 2 3 4 5 6 7 8 9]


**Task 3**: Generate a two-dimensional NumPy array with random values and print its shape and data type.

In [ ]:
# Write your answer from this cell onwards


In [ ]:
import numpy as np
abc = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7,8,9],
    ])
print(abc)
print(type(abc))
print(np.shape(abc))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)


**Task 4**: Create a NumPy array with 50 evenly spaced values between 0 and 10.

In [ ]:
# Write your answer from this cell onwards

In [ ]:
evenly_spaced_array = np.linspace(0, 10, 50)
evenly_spaced_array

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

**Task 5**: Write a program to demonstrate the difference between a Python list and a NumPy array by performing element-wise addition on both.

In [ ]:
# Write your answer from this cell onwards


In [ ]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]

try:
    list_sum = list1 + list2
    print(f"List addition (concatenation): {list_sum}")
except TypeError as e:
    print(f"List addition error: {e}")

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

array_sum = array1 + array2
print(f"NumPy array addition (element-wise): {array_sum}")

List addition (concatenation): [1, 2, 3, 4, 5, 6]
NumPy array addition (element-wise): [5 7 9]


---

#### **2. Creation of NumPy Arrays**

**Task 6**: Create a NumPy array of all zeros with a shape of (3, 4).

In [ ]:
# Write your answer from this cell onwards


In [ ]:
p = np.zeros((3, 4), dtype=int)
print(p)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


**Task 7**: Create a NumPy array of all ones with a shape of (2, 5) and a data type of float.

In [ ]:
# Write your answer from this cell onwards


In [ ]:
p = np.ones((2, 5), dtype=float)
print(p)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


**Task 8**: Use `arange()` to create a NumPy array containing numbers from 10 to 50 with a step of 5.

In [ ]:
# Write your answer from this cell onwards


In [ ]:
np.arange(10,55,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

**Task 9**: Generate a 3x3 identity matrix using NumPy.

In [ ]:
# Write your answer from this cell onwards


In [ ]:
identity_matrix = np.identity(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Task 10**: Create a 4x4 array filled with random integers between 1 and 20.

In [ ]:
# Write your answer from this cell onwards


In [ ]:
random_array = np.random.randint(1, 21, size = (4, 4))
print(random_array)

[[15 17 16  2]
 [ 9 16 16 10]
 [12  7 16 20]
 [ 8  3 17 12]]


---

#### **3. Indexing and Slicing of NumPy Arrays**

**Task 11**: Create a 1D NumPy array with values ranging from 1 to 15. Slice the array to extract elements from index 3 to 8.

In [ ]:
# Write your answer from this cell onwards


In [ ]:
array_1d = np.arange(1, 16)
array_1d
sliced_array = array_1d[3:9]
sliced_array
print(f"Original Array: {array_1d}")
print(f"Sliced Array: {sliced_array}")

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Sliced Array: [4 5 6 7 8]


**Task 12**: Generate a 3x3 matrix with values ranging from 1 to 9. Retrieve the element at the second row and third column.

In [ ]:
# Write your answer from this cell onwards


In [ ]:
matrix = np.arange(1, 10).reshape(3, 3)
element = matrix[1, 2]
print(matrix)
element

[[1 2 3]
 [4 5 6]
 [7 8 9]]


6

**Task 13**: Slice a 4x4 array to extract the last two rows and the last two columns.

In [ ]:
# Write your answer from this cell onwards


In [ ]:
array_4x4 = np.random.randint(1, 21, size = (4, 4))
print(f"Original Array: {array_4x4}")
sliced_array = array_4x4[2:, 2:]
print(f"Sliced Array: {sliced_array}")

Original Array: [[ 3  4 19  5]
 [ 4  4  6  5]
 [ 5 17  6 14]
 [ 9 13  3 11]]
Sliced Array: [[ 6 14]
 [ 3 11]]


**Task 14**: Create a 5x5 matrix of random integers between 10 and 50. Replace all elements in the first row with the value 100.

In [ ]:
# Write your answer from this cell onwards


In [ ]:
matrix_1 = np.random.randint(1, 21, size = (5, 5))
print(f"Original matrix: {matrix_1}")
matrix_1[0, :] = 100
print(f"Matirx after replacing first row with 100: {matrix_1}")

Original matrix: [[ 7 10 14 15 19]
 [14  4 17  7  9]
 [ 1  9 16 13 12]
 [13 13 19  8 11]
 [ 3 10  6 18 20]]
Matirx after replacing first row with 100: [[100 100 100 100 100]
 [ 14   4  17   7   9]
 [  1   9  16  13  12]
 [ 13  13  19   8  11]
 [  3  10   6  18  20]]


**Task 15**: Create a 1D NumPy array of 10 elements. Use boolean indexing to filter out all values greater than 5.

In [ ]:
# Write your answer from this cell onwards


In [ ]:
array_1d = np.arange(10)
print(f"Original array: {array_1d}")

boolean = array_1d > 5
print(f"Boolean: {boolean}")

filtered_array = array_1d[boolean]
print(f"Filtered array (values greater than 5): {filtered_array}")

Original array: [0 1 2 3 4 5 6 7 8 9]
Boolean: [False False False False False False  True  True  True  True]
Filtered array (values greater than 5): [6 7 8 9]
