#### **Task 1: Perform Mathematical Operations on NumPy Arrays**

1. Create two 1D arrays of size 5 with random integers between 1 and 10.

In [ ]:
# Write your answer from this cell onwards


In [2]:
import numpy as np
array1 = np.random.randint(1, 11, size=5)
array2 = np.random.randint(1, 11, size=5)
print(array1)
print(array2)

[ 5  8 10  7  1]
[4 1 3 4 5]


2. Perform the following mathematical operations on these arrays:
   - Element-wise addition
   - Element-wise subtraction
   - Element-wise multiplication
   - Element-wise division

In [ ]:
# Write your answer from this cell onwards


In [7]:
element_wise_addition = array1 + array2
print(element_wise_addition)

element_wise_subtraction = array1 - array2
print(element_wise_subtraction)

element_wise_multiplication = array1 * array2
print(element_wise_multiplication)

element_wise_division = array1 / array2
print(element_wise_division)

[ 9  9 13 11  6]
[ 1  7  7  3 -4]
[20  8 30 28  5]
[1.25       8.         3.33333333 1.75       0.2       ]


3. Compute the dot product of the two arrays.

In [ ]:
# Write your answer from this cell onwards


In [8]:
dot = np.dot(array1, array2)
dot

91

#### **Task 2: Combine and Split Arrays**

1. Create two 2D arrays of shape (3, 3) with random integers between 1 and 20.

In [ ]:
# Write your answer from this cell onwards


In [16]:
array3_2d = np.random.randint(1, 21, size=(3, 3))
print(f"Array3: {array3_2d}")
array4_2d = np.random.randint(1, 21, size=(3, 3))
print(f"Array4: {array4_2d}")

Array3: [[12  3 18]
 [ 1  7  8]
 [12 16  7]]
Array4: [[19  8 10]
 [ 8 20  8]
 [12 15 18]]


2. Combine these arrays:
   - Vertically using `vstack`
   - Horizontally using `hstack`

In [ ]:
# Write your answer from this cell onwards


In [19]:
vstack = np.vstack((array3_2d, array4_2d))
print(f"vstack: {vstack}")

hstack = np.hstack((array3_2d, array4_2d))
print(f"hstack: {hstack}")

vstack: [[12  3 18]
 [ 1  7  8]
 [12 16  7]
 [19  8 10]
 [ 8 20  8]
 [12 15 18]]
hstack: [[12  3 18 19  8 10]
 [ 1  7  8  8 20  8]
 [12 16  7 12 15 18]]


3. Split the combined array back into the original two arrays using `vsplit` and `hsplit`.

In [ ]:
# Write your answer from this cell onwards


In [20]:
vsplit = np.vsplit(vstack, 2)
print(f"vsplit: {vsplit}")

hsplit = np.hsplit(hstack, 2)
print(f"hsplit: {hsplit}")

vsplit: [array([[12,  3, 18],
       [ 1,  7,  8],
       [12, 16,  7]]), array([[19,  8, 10],
       [ 8, 20,  8],
       [12, 15, 18]])]
hsplit: [array([[12,  3, 18],
       [ 1,  7,  8],
       [12, 16,  7]]), array([[19,  8, 10],
       [ 8, 20,  8],
       [12, 15, 18]])]


#### **Task 3: Search, Sort, and Filter in Arrays**

1. Create a 1D array with 10 random integers between 1 and 50.

In [ ]:
# Write your answer from this cell onwards


In [21]:
array5 = np.random.randint(1, 51, size=10)
print(f"array5: {array5}")
array6 = np.random.randint(1, 51, size=10)
print(f"array6: {array6}")

array5: [40  9 32 44 48  3  7 31 26 41]
array6: [47 19 34 48 49 41  6  6  9 49]


2. Find the indices of elements that are greater than 25.

In [ ]:
# Write your answer from this cell onwards


In [23]:
elements = array5 > 25
print(f"Elements: {elements}")
indices = np.where(elements)
print(indices)

elements = array6 > 25
print(f"Elements: {elements}")
indices = np.where(elements)
print(indices)

Elements: [ True False  True  True  True False False  True  True  True]
(array([0, 2, 3, 4, 7, 8, 9]),)
Elements: [ True False  True  True  True  True False False False  True]
(array([0, 2, 3, 4, 5, 9]),)


3. Sort the array in ascending order.

In [ ]:
# Write your answer from this cell onwards


In [24]:
sorted_array5 = np.sort(array5)
print(f"Original Array5: {array5}")
print(f"sorted_array5: {sorted_array5}")
sorted_array6 = np.sort(array6)
print(f"Original Array6: {array6}")
print(f"sorted_array6: {sorted_array6}")

Original Array5: [40  9 32 44 48  3  7 31 26 41]
sorted_array5: [ 3  7  9 26 31 32 40 41 44 48]
Original Array6: [47 19 34 48 49 41  6  6  9 49]
sorted_array6: [ 6  6  9 19 34 41 47 48 49 49]


4. Filter the array to include only even numbers.

In [ ]:
# Write your answer from this cell onwards


In [25]:
array5_even = array5[array5 % 2 == 0]
print(f"Original Array5: {array5_even}")
print(f"array5_even: {array5_even}")

array6_even = array6[array6 % 2 == 0]
print(f"Original Array6: {array6_even}")
print(f"array6_even: {array6_even}")

Original Array5: [40 32 44 48 26]
array5_even: [40 32 44 48 26]
Original Array6: [34 48  6  6]
array6_even: [34 48  6  6]


#### **Task 4: Aggregate Functions**

1. Create a 2D array of shape (4, 5) with random integers between 10 and 100.

In [ ]:
# Write your answer from this cell onwards


In [26]:
array7 = np.random.randint(10, 101, size=(4, 5))
print(f"array7: {array7}")
array8 = np.random.randint(10, 101, size=(4, 5))
print(f"array8: {array8}")

array7: [[53 83 46 13 38]
 [42 63 46 55 43]
 [75 10 52 16 24]
 [12 83 63 28 59]]
array8: [[ 12  22  99  50  65]
 [100 100  60  32  91]
 [ 16  98  38  39  41]
 [ 23  16  55  68  59]]


2. Perform the following aggregate operations:
   - Compute the sum of all elements.
   - Find the maximum and minimum values in the array.
   - Compute the mean and standard deviation of the elements.
   - Find the sum of elements along each row and each column.

In [ ]:
# Write your answer from this cell onwards


In [29]:
sum_of_elements = np.sum(array7)
print(f"sum_of_elements of array7: {sum_of_elements}")
sum_of_elements = np.sum(array8)
print(f"sum_of_elements of array8: {sum_of_elements}")

max_value = np.max(array7)
print(f"max_value of array7: {max_value}")
max_value = np.max(array8)
print(f"max_value of array8: {max_value}")

min_value = np.min(array7)
print(f"min_value of array7: {min_value}")
min_value = np.min(array8)
print(f"min_value of array8: {min_value}")

mean_value = np.mean(array7)
print(f"mean_value of array7: {mean_value}")
mean_value = np.mean(array8)
print(f"mean_value of array8: {mean_value}")

std_value = np.std(array7)
print(f"std_value of array7: {std_value}")
std_value = np.std(array8)
print(f"std_value of array8: {std_value}")

sum_of_elements of array7: 904
sum_of_elements of array8: 1084
max_value of array7: 83
max_value of array8: 100
min_value of array7: 10
min_value of array8: 12
mean_value of array7: 45.2
mean_value of array8: 54.2
std_value of array7: 22.15536052516411
std_value of array8: 29.771798736388096


#### **Task 5: Statistical Functions**

1. Create a 2D array of shape (5, 5) with random integers between 1 and 50.

In [ ]:
# Write your answer from this cell onwards


In [31]:
array9 = np.random.randint(1, 50, size=(5, 5))
print(f"array9: {array9}")
array10 = np.random.randint(1, 50, size=(5, 5))
print(f"array10: {array10}")

array9: [[36  1  8 13  7]
 [32 41  1 29 43]
 [ 4 36  3 22 40]
 [22 36 34 35  6]
 [29  9 35 22 45]]
array10: [[47 22  2 32 49]
 [15 45 12 18 35]
 [ 2  3 49 47  8]
 [15  3 18  1 36]
 [29 15  7 31 20]]


2. Compute the following statistics:
   - Median of all elements.
   - Variance of the elements.
   - Cumulative sum along each row.
   - Cumulative product along each column.

In [ ]:
# Write your answer from this cell onwards


In [32]:
meadian = np.median(array9)
print(f"meadian of array9: {meadian}")
meadian = np.median(array10)
print(f"meadian of array10: {meadian}")

variance = np.var(array9)
print(f"variance of array9: {variance}")
variance = np.var(array10)
print(f"variance of array10: {variance}")

cumulative_sum = np.cumsum(array9, axis=1)
print(f"cumulative_sum of array9: {cumulative_sum}")
cumulative_sum = np.cumsum(array10, axis=1)
print(f"cumulative_sum of array10: {cumulative_sum}")

cumulative_product = np.cumprod(array9, axis=0)
print(f"cumulative_product of array9: {cumulative_product}")
cumulative_product = np.cumprod(array10, axis=0)
print(f"cumulative_product of array10: {cumulative_product}")

meadian of array9: 29.0
meadian of array10: 18.0
variance of array9: 214.2464
variance of array10: 259.7664
cumulative_sum of array9: [[ 36  37  45  58  65]
 [ 32  73  74 103 146]
 [  4  40  43  65 105]
 [ 22  58  92 127 133]
 [ 29  38  73  95 140]]
cumulative_sum of array10: [[ 47  69  71 103 152]
 [ 15  60  72  90 125]
 [  2   5  54 101 109]
 [ 15  18  36  37  73]
 [ 29  44  51  82 102]]
cumulative_product of array9: [[     36       1       8      13       7]
 [   1152      41       8     377     301]
 [   4608    1476      24    8294   12040]
 [ 101376   53136     816  290290   72240]
 [2939904  478224   28560 6386380 3250800]]
cumulative_product of array10: [[     47      22       2      32      49]
 [    705     990      24     576    1715]
 [   1410    2970    1176   27072   13720]
 [  21150    8910   21168   27072  493920]
 [ 613350  133650  148176  839232 9878400]]


#### **Task 6: Combine All Concepts**

1. Create a dataset using a 2D NumPy array with random integers between 1 and 100, where rows represent students and columns represent their scores in 5 subjects.

In [34]:
# Write your answer from this cell onwards


In [35]:
data_set = np.random.randint(1, 101, size=(10, 5))
print(f"data_set: {data_set}")

data_set: [[93 70 60 26 43]
 [28 86 11 34 65]
 [21 43 46 27 74]
 [23 84 12 23 22]
 [63 43 26 56 19]
 [57 16 24 60 48]
 [ 5 61 21 21 89]
 [22 70 81 50 14]
 [58 33 85  8 99]
 [68 91  7 51  2]]


2. Perform the following:
   - Compute the total score for each student.
   - Find the student with the highest and lowest total score.
   - Sort the array based on total scores.
   - Filter students who scored more than 75 in at least three subjects.

In [36]:
# Write your answer from this cell onwards


In [37]:
total_score = np.sum(data_set, axis=1)
print(f"total_score: {total_score}")

highest_score = np.max(total_score)
print(f"highest_score: {highest_score}")

lowest_score = np.min(total_score)
print(f"lowest_score: {lowest_score}")

sorted_array = np.sort(total_score)
print(f"sorted_array: {sorted_array}")

filtered_array = data_set[np.where(np.sum(data_set[:, 3:] > 75, axis=1) >= 3)]
print(f"filtered_array: {filtered_array}")


total_score: [292 224 211 164 207 205 197 237 283 219]
highest_score: 292
lowest_score: 164
sorted_array: [164 197 205 207 211 219 224 237 283 292]
filtered_array: []
